spring:
  application:
    name: idolbom_api

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/idolbom
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  output:
    ansi:
      enabled: always

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

#Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: kr.go.mogef.idolbom_api.sample.dto
  configuration:
    map-underscore-to-camel-case: true